### ISSUE TITLE
Broken link (on innogames.com)

### ISSUE THREAD

**Issue by theCalcaholic** [svenstaro/innojam8#1]
Der Link vom innogames gamejam verweist noch immer auf "http://svenstaro.github.io/innojam8/dev.html". Diese Datei existiert aber nicht mehr.

Possible fixes:
1. "dev.html" mit einer Weiterleitung auf /index.html erstellen.
2. Anpassen des Link bei innogames.com, falls berechtigt.

**Comment by raffomania** [comment]
Fixed. Vielen Dank für den Hinweis!
